### ISSUE TITLE
TypeError: No_Logger.__init__() got an unexpected keyword argument 'prefix'

### ISSUE THREAD

**Issue by NathanMolinier** [Hendrik-code/spineps#23]
## Description

I tried to use spineps on the last commit (tag: v1.0.9) and got this error.

<img width="1015" alt="Screenshot 2024-06-19 at 13 28 44" src="https://github.com/Hendrik-code/spineps/assets/68945192/2b18eb1d-ff67-4ccd-87a7-eae8610031ab">

## To reproduce

1. Clone spineps
2. Create a virtual environment using python=3.11
3. Run `pip install -e .` in the venv
4. Install [torch](https://pytorch.org/get-started/locally/) using `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu`
5. Checkout to the current commit `git checkout v1.0.9`
6. Run `spineps sample -i ./test/sub-amu01_T1w.nii.gz -model_semantic t1w_segmentor -model_instance inst_vertebra_3.0 -dn derivatives -cpu`

## Environment

MacOS Sonoma Version 14.2

**Comment by Hendrik-code** [comment]
ahh interesting. Then your TPTBox package version is too old. The requirements of spineps should reflect this. But gonna check this tomorrow.

**Comment by NathanMolinier** [comment]
It worked thanks !
