### ISSUE TITLE
Make the code more flexible with file naming conventions

### ISSUE THREAD

**Issue by NathanMolinier** [Hendrik-code/spineps#24]
## Description

Spineps fails to compile when encountering files with different naming conventions. Can it be made more flexible, or can a flag be added to limit these preprocessing checks ?

I understand the importance of pushing BIDS forward, but I believe these checks and errors might discourage people from using the tool.

![image](https://github.com/Hendrik-code/spineps/assets/68945192/c4a76715-521f-4011-a096-d51cb2ad1e6f)

## To Reproduce
- Name a file with the entity `acq-mprage` and run spineps

**Comment by Hendrik-code** [comment]
If you set both
ignore_bids_filter: bool = False,
ignore_compatibility_issues: bool = False,

to True, SPINEPS should not check anything in that regard anymore.
