### ISSUE TITLE
import issues:   install again failed,some package not installed whole

### ISSUE THREAD

**Issue by kongfanyu06** [Hendrik-code/spineps#9]
import issues

pip install -e . not install all package whole
and try installing via the requirements again, not succcess

We only download the source package code and install success, Is there any other solution?

**Comment by Hendrik-code** [comment]
Hey @kongfanyu06 
Thanks for the issue. Could you provide more detailed information?
Which python version, OS, ... I cannot reproduce the bug otherwise. What exactly failed, what was the error, ...?

Best regards
Hendrik
